modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/shmove/cat_jam/issues"
license = "CC-BY-NC-SA-4.0"

[[mods]]
modId = "cat_jam"
version = "${version}"
displayName = "cat_jam"
displayURL="https://github.com/shmove/cat_jam"
authors = "shmove"
description = '''makes cats jam to the rhythm of music discs :3'''
logoFile = "assets/cat_jam/icon.png"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.cat_jam]]
modId = "forge"
mandatory = true
versionRange = "[${loader_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cat_jam]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.cat_jam]]
modId = "alexsmobs"
mandatory = false
versionRange = "*"
ordering = "AFTER"

[[dependencies.cat_jam]]
modId = "quark"
mandatory = false
versionRange = "*"
ordering = "AFTER"
