modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/shmove/cat_jam/issues"
license = "CC-BY-NC-SA-4.0"

[[mods]]
modId = "cat_jam"
version = "${version}"
displayName = "cat_jam"
displayURL="https://github.com/shmove/cat_jam"
authors = "shmove"
description = '''makes cats jam to the rhythm of music discs :3'''
logoFile = "icon.png"

[[dependencies.cat_jam]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cat_jam]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"