modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/shmove/cat_jam/issues"
license = "CC-BY-NC-SA-4.0"

[[mods]]
modId = "cat_jam"
version = "${version}"
displayName = "cat_jam"
displayURL="https://github.com/shmove/cat_jam"
authors = "shmove"
description = '''makes cats jam to the rhythm of music discs :3'''
logoFile = "assets/cat_jam/icon.png"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.cat_jam]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cat_jam]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.cat_jam]]
modId = "alexsmobs"
type = "optional"
ordering = "AFTER"

[[dependencies.cat_jam]]
modId = "quark"
type = "optional"
ordering = "AFTER"

[[mixins]]
config = "cat_jam.mixins.json"
